[package]
name = "tauri-plugin-deep-link"
version = "0.0.0"
authors = ["FabianLars <fabianlars@fabianlars.de>"]
description = "A Tauri plugin for deep linking support"
edition = "2021"
rust-version = "1.56"
exclude = ["/examples"]
license = "MIT"

[dependencies]
dirs-next = "2.0"
log = "0.4.17"
once_cell = "1.12"
tauri-utils = { version = "1.0.1" }

[target.'cfg(windows)'.dependencies]
interprocess = { git = "https://github.com/kotauskas/interprocess", rev = "e9bd7c1eaadb73497e26842ec70faea7e554e8e9", default-features = false }
winreg = "0.10.1"
